CREATE DATABASE login;
USE login;

CREATE TABLE usuarios(
	USU_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USU_LOGIN VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR(100) NOT NULL
);

USE login;
INSERT INTO usuarios (USU_LOGIN, USU_SENHA)
VALUES ("administrador", "admin123");